#!/bin/sh
# Generated by Binloom @BINLOOM_VERSION@. Do not edit.
set -eu

BINLOOMW_VERSION="@BINLOOM_VERSION@"

ROOT_DIR=$(CDPATH='' cd "$(dirname "$0")" && pwd)
LOCKFILE="$ROOT_DIR/binloom.lock"

if [ ! -f "$LOCKFILE" ]; then
    echo "error: binloom.lock not found" >&2
    exit 1
fi

case "$(uname -s)" in
    Darwin) OS="macos" ;;
    Linux) OS="linux" ;;
    *)
        echo "error: unsupported operating system: $(uname -s)" >&2
        exit 1
        ;;
esac

case "$(uname -m)" in
    arm64 | aarch64) ARCH="aarch64" ;;
    x86_64 | amd64) ARCH="x86_64" ;;
    *)
        echo "error: unsupported architecture: $(uname -m)" >&2
        exit 1
        ;;
esac

PLATFORM="$OS-$ARCH"

read_lock_value() {
    section="$1"
    key="$2"

    awk -v section="[$section]" -v key="$key" '
        $0 == section {
            inside = 1
            next
        }

        inside && /^\[/ {
            exit
        }

        inside {
            line = $0

            if (line ~ "^[[:space:]]*" key "[[:space:]]*=") {
                sub(/^[^=]*=[[:space:]]*"/, "", line)
                sub(/".*$/, "", line)
                print line
                exit
            }
        }
    ' "$LOCKFILE"
}

download_file() {
    if command -v curl >/dev/null 2>&1; then
        curl --fail --location --silent --show-error \
            --output "$2" \
            "$1"
    elif command -v wget >/dev/null 2>&1; then
        wget --quiet --output-document="$2" "$1"
    else
        echo "error: curl or wget is required to download files" >&2
        return 1
    fi
}

sha256_file() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        echo "error: sha256sum or shasum is required to verify files" >&2
        return 1
    fi
}

verify_file() {
    actual_sha256=$(sha256_file "$1")

    if [ "$actual_sha256" != "$2" ]; then
        echo "error: $3 checksum mismatch" >&2
        echo "expected: $2" >&2
        echo "actual:   $actual_sha256" >&2
        return 1
    fi
}

LOCKED_WRAPPER_VERSION=$(read_lock_value "wrapper" "version")
WRAPPER_URL=$(read_lock_value "wrapper" "url")
WRAPPER_SHA256=$(read_lock_value "wrapper" "sha256")
WRAPPER_PATH="$ROOT_DIR/binloomw"

if [ -n "${LOCKED_WRAPPER_VERSION}${WRAPPER_URL}${WRAPPER_SHA256}" ]; then
    if [ -z "$LOCKED_WRAPPER_VERSION" ] ||
        [ -z "$WRAPPER_URL" ] ||
        [ -z "$WRAPPER_SHA256" ]; then
        echo "error: incomplete wrapper lock data" >&2
        exit 1
    fi

    CURRENT_WRAPPER_SHA256=$(sha256_file "$WRAPPER_PATH")

    if [ "$BINLOOMW_VERSION" != "$LOCKED_WRAPPER_VERSION" ] ||
        [ "$CURRENT_WRAPPER_SHA256" != "$WRAPPER_SHA256" ]; then
        WRAPPER_TMP=$(mktemp "$ROOT_DIR/.binloomw.XXXXXX")

        cleanup_wrapper() {
            rm -f "$WRAPPER_TMP"
        }

        trap cleanup_wrapper EXIT HUP INT TERM

        download_file "$WRAPPER_URL" "$WRAPPER_TMP"
        verify_file "$WRAPPER_TMP" "$WRAPPER_SHA256" "Binloom wrapper"

        chmod 755 "$WRAPPER_TMP"
        mv "$WRAPPER_TMP" "$WRAPPER_PATH"

        trap - EXIT HUP INT TERM

        exec "$WRAPPER_PATH" "$@"
    fi
fi

VERSION=$(read_lock_value "binloom" "version")
ARTIFACT_SECTION="binloom.artifacts.$PLATFORM"
URL=$(read_lock_value "$ARTIFACT_SECTION" "url")
SHA256=$(read_lock_value "$ARTIFACT_SECTION" "sha256")
FORMAT=$(read_lock_value "$ARTIFACT_SECTION" "format")

if [ -z "$VERSION" ] || [ -z "$URL" ] || [ -z "$SHA256" ] || [ -z "$FORMAT" ]; then
    echo "error: incomplete Binloom lock data for $PLATFORM" >&2
    exit 1
fi

INSTALL_DIR="$ROOT_DIR/.tools/binloom/$VERSION"
BINLOOM="$INSTALL_DIR/binloom"

if [ -x "$BINLOOM" ]; then
    exec "$BINLOOM" "$@"
fi

mkdir -p "$INSTALL_DIR"

ARCHIVE=$(mktemp "$INSTALL_DIR/.download.XXXXXX")
BINARY_TMP=$(mktemp "$INSTALL_DIR/.binloom.XXXXXX")

cleanup() {
    rm -f "$ARCHIVE" "$BINARY_TMP"
}

trap cleanup EXIT HUP INT TERM

download_file "$URL" "$ARCHIVE"

verify_file "$ARCHIVE" "$SHA256" "Binloom"

case "$FORMAT" in
    gz)
        gzip -dc "$ARCHIVE" > "$BINARY_TMP"
        ;;
    raw)
        cp "$ARCHIVE" "$BINARY_TMP"
        ;;
    *)
        echo "error: unsupported Binloom asset format: $FORMAT" >&2
        exit 1
        ;;
esac

chmod 755 "$BINARY_TMP"
mv "$BINARY_TMP" "$BINLOOM"

rm -f "$ARCHIVE"
trap - EXIT HUP INT TERM

exec "$BINLOOM" "$@"