use crate::common;
use anyhow::{Context, Result};
use std::os::unix::fs::PermissionsExt;
use std::{
    fs::{self, OpenOptions},
    io::{self, Write},
    path::Path,
};

pub fn init() -> Result<()> {
    println!("Initializing Binloom...");
    let manifest_path = Path::new("binloom.toml");
    let wrapper_path = Path::new("binloomw");

    if manifest_path
        .try_exists()
        .context("failed to check binloom.toml")?
    {
        common::warn("binloom.toml already exists; keeping it");
    } else {
        generate_manifest(manifest_path).context("failed to create binloom.toml")?;
        println!("Created binloom.toml");
    }

    if wrapper_path
        .try_exists()
        .context("failed to check binloomw")?
    {
        common::warn("binloomw already exists; keeping it");
    } else {
        generate_binloomw(wrapper_path).context("failed to create binloomw")?;
        println!("Created binloomw");
    }

    if add_to_gitignore(Path::new(".gitignore")).context("failed to update .gitignore")? {
        println!("Added .tools/ to .gitignore");
    }

    Ok(())
}

fn generate_manifest(path: &Path) -> io::Result<()> {
    let manifest = format!(
        r#"#:schema https://raw.githubusercontent.com/KyrboForge/binloom/main/schemas/binloom.schema.json

manifest-version = 1

[binloom]
version = "{}"
"#,
        env!("CARGO_PKG_VERSION")
    );
    let mut file = OpenOptions::new().write(true).create_new(true).open(path)?;

    file.write_all(manifest.as_bytes())
}
fn add_to_gitignore(path: &Path) -> io::Result<bool> {
    let existing = match fs::read_to_string(path) {
        Ok(content) => content,
        Err(error) if error.kind() == io::ErrorKind::NotFound => String::new(),
        Err(error) => return Err(error),
    };

    if existing.lines().any(|line| line.trim() == ".tools/") {
        return Ok(false);
    }

    let mut file = OpenOptions::new().create(true).append(true).open(path)?;

    if !existing.is_empty() && !existing.ends_with('\n') {
        writeln!(file)?;
    }

    writeln!(file, ".tools/")?;

    Ok(true)
}

fn generate_binloomw(path: &Path) -> io::Result<()> {
    let mut file = OpenOptions::new().write(true).create_new(true).open(path)?;
    let wrapper =
        include_str!("binloomw.sh").replace("@BINLOOM_VERSION@", env!("CARGO_PKG_VERSION"));

    file.write_all(wrapper.as_bytes())?;

    let mut permissions = file.metadata()?.permissions();
    permissions.set_mode(0o755);
    file.set_permissions(permissions)
}

#[cfg(test)]
mod tests {
    use crate::init::{add_to_gitignore, generate_binloomw, generate_manifest};
    use crate::platform::Platform;
    use sha2::{Digest, Sha256};
    use std::os::unix::fs::PermissionsExt;
    use std::{fs, io, process::Command};

    #[test]
    fn generates_manifest_without_overwriting_it() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("binloom.toml");

        generate_manifest(&path).unwrap();

        let expected = format!(
            r#"#:schema https://raw.githubusercontent.com/KyrboForge/binloom/main/schemas/binloom.schema.json

manifest-version = 1

[binloom]
version = "{}"
"#,
            env!("CARGO_PKG_VERSION")
        );

        assert_eq!(fs::read_to_string(&path).unwrap(), expected);

        let error = generate_manifest(&path).unwrap_err();

        assert_eq!(error.kind(), io::ErrorKind::AlreadyExists);
        assert_eq!(fs::read_to_string(path).unwrap(), expected);
    }

    #[test]
    fn adds_tools_to_gitignore_once_without_replacing_content() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join(".gitignore");

        fs::write(&path, "target/\n.env").unwrap();

        assert!(add_to_gitignore(&path).unwrap());
        assert_eq!(
            fs::read_to_string(&path).unwrap(),
            "target/\n.env\n.tools/\n"
        );

        assert!(!add_to_gitignore(&path).unwrap());
        assert_eq!(
            fs::read_to_string(path).unwrap(),
            "target/\n.env\n.tools/\n"
        );
    }

    #[test]
    fn generates_executable_wrapper_without_overwriting_it() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("binloomw");

        generate_binloomw(&path).unwrap();

        let content = fs::read_to_string(&path).unwrap();
        assert!(content.starts_with("#!/bin/sh\n"));

        let mode = fs::metadata(&path).unwrap().permissions().mode();
        assert_ne!(mode & 0o111, 0);

        let error = generate_binloomw(&path).unwrap_err();
        assert_eq!(error.kind(), io::ErrorKind::AlreadyExists);

        assert!(content.contains(&format!(
            "# Generated by Binloom {}. Do not edit.",
            env!("CARGO_PKG_VERSION")
        )));
        assert!(content.contains(&format!(
            "BINLOOMW_VERSION=\"{}\"",
            env!("CARGO_PKG_VERSION")
        )));
        assert!(!content.contains("@BINLOOM_VERSION@"));
    }

    #[test]
    fn wrapper_bootstraps_and_reuses_cached_binloom() {
        let directory = tempfile::tempdir().unwrap();
        let wrapper = directory.path().join("binloomw");
        let asset = directory.path().join("fake-binloom");

        let fake_binary = br#"#!/bin/sh
printf 'fake binloom: %s\n' "$*"
"#;

        fs::write(&asset, fake_binary).unwrap();
        generate_binloomw(&wrapper).unwrap();

        let checksum = Sha256::digest(fake_binary)
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();

        let platform = Platform::current().unwrap();

        fs::write(
            directory.path().join("binloom.lock"),
            format!(
                r#"lock-version = 1

[binloom]
version = "test"

[binloom.artifacts.{platform}]
url = "file://{}"
sha256 = "{checksum}"
format = "raw"
"#,
                asset.display()
            ),
        )
        .unwrap();

        let run = || {
            Command::new(&wrapper)
                .args(["hello", "world"])
                .output()
                .unwrap()
        };

        let first = run();
        assert!(first.status.success());
        assert_eq!(
            String::from_utf8(first.stdout).unwrap(),
            "fake binloom: hello world\n"
        );

        fs::remove_file(asset).unwrap();

        let second = run();
        assert!(second.status.success());
        assert_eq!(
            String::from_utf8(second.stdout).unwrap(),
            "fake binloom: hello world\n"
        );

        assert!(
            directory
                .path()
                .join(".tools/binloom/test/binloom")
                .is_file()
        );
    }
}
